### ISSUE TITLE
Añadir guía para renombrar el proyecto

### ISSUE THREAD

**Issue by JRrodrigurez** [AstroCorp/React-Native-Base-App#248]
Hola, gracias por publicar tu base. 
Estoy tratando de usarla, cambié el nombre del proyecto con react-native-rename, pero una vez emulando quedan dependencias corruptas. 

Tienes otra forma de cambiarle el nombre?

He intentado corregir algunas dependencias a mano, imagino que quizas hay otra forma.

Saludos

**Comment by AstroCorp** [comment]
¿Qué errores tienes? He usado esta base en 2 proyectos y los renombre sin problemas.

**Comment by JRrodrigurez** [comment]
Ejecute en este orden:

1. git

git clone (OK)
2. 2) react-native-rename pruebaMercadoApp -b cl.pruebamercadoapp    (OK)
3. 3) yarn install (OK)
4. 4) pod install   (NOK)

   Tu snapshot Podfile.lock está en el repo y pide la version (= 0.2.5, ~> 0.2.3) de SDWebImageWebPCoder.
No se si es lo correcto, pero luego de borrar el cache de los Pods, borré el .lock, y le di "pod install", finalmente instaló la versión 0.4.1 
5) react-native (NOK)
Faltaban dos archivos
- ~/React-Native-Base-App/ios/pruebamercadoapp-Bridging-Header.h 
- ~/React-Native-Base-App/ios/mercadoVecino/pruebamercadoappDelegate.m

pero existían:
- App-Bridging-Header.h
- AppDelegate.m

Los renombre, pero continuaron otros errores. 
No creo que sea el problema.

**Comment by AstroCorp** [comment]
En cuanto tenga tiempo crearé una guía para renombrar el proyecto.

**Comment by AstroCorp** [comment]
@JRrodrigurez acabo de subir los cambios para que el renombrado funcione, lo he probado con react-native-rename pruebaMercadoApp -b cl.pruebamercadoapp y todo correcto. He añadido al readme  los pasos que he seguido para que funcione todo correctamente
